# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
cache: packages
warnings_are_errors: false

r:
- 3.1
- 3.2
- oldrel
- release
- devel

matrix:
  allow_failures:
    - r: 3.1

r_packages: 
  - covr
 
after_success:
- Rscript -e 'covr::codecov()'
