# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/

language: R
sudo: false
cache: packages
warnings_are_errors: false

env:
  global:
  - MAKEFLAGS="-j 2"


matrix:
  fast_finish: true
  include:
  - r: devel
    after_success:
      - find . -name testthat.Rout | xargs cat        
    after_failure:
      - find . -name testthat.Rout | xargs cat
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    - find . -name testthat.Rout | xargs cat
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("tidyverse/tidytemplate")'
    after_failure:
      - find . -name testthat.Rout | xargs cat
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2

r_packages: 
  - covr
  